{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "ExceptionHandler.java",
  "functionName": "toCause",
  "functionId": "toCause___e-Exception",
  "sourceFilePath": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/web/webhdfs/ExceptionHandler.java",
  "functionStartLine": 95,
  "functionEndLine": 114,
  "numCommitsSeen": 6,
  "timeTaken": 1020,
  "changeHistory": [
    "bf8e4332cb4c33d0287ae6ecca61b335402ac1c4"
  ],
  "changeHistoryShort": {
    "bf8e4332cb4c33d0287ae6ecca61b335402ac1c4": "Yintroduced"
  },
  "changeHistoryDetails": {
    "bf8e4332cb4c33d0287ae6ecca61b335402ac1c4": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-7279. Use netty to implement DatanodeWebHdfsMethods. Contributed by Haohui Mai.\n",
      "commitDate": "17/11/14 11:42 AM",
      "commitName": "bf8e4332cb4c33d0287ae6ecca61b335402ac1c4",
      "commitAuthor": "Haohui Mai",
      "diff": "@@ -0,0 +1,20 @@\n+  private static Exception toCause(Exception e) {\n+    final Throwable t \u003d e.getCause();\n+    if (e instanceof SecurityException) {\n+      // For the issue reported in HDFS-6475, if SecurityException\u0027s cause\n+      // is InvalidToken, and the InvalidToken\u0027s cause is StandbyException,\n+      // return StandbyException; Otherwise, leave the exception as is,\n+      // since they are handled elsewhere. See HDFS-6588.\n+      if (t !\u003d null \u0026\u0026 t instanceof SecretManager.InvalidToken) {\n+        final Throwable t1 \u003d t.getCause();\n+        if (t1 !\u003d null \u0026\u0026 t1 instanceof StandbyException) {\n+          e \u003d (StandbyException)t1;\n+        }\n+      }\n+    } else {\n+      if (t !\u003d null \u0026\u0026 t instanceof Exception) {\n+        e \u003d (Exception)t;\n+      }\n+    }\n+    return e;\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private static Exception toCause(Exception e) {\n    final Throwable t \u003d e.getCause();\n    if (e instanceof SecurityException) {\n      // For the issue reported in HDFS-6475, if SecurityException\u0027s cause\n      // is InvalidToken, and the InvalidToken\u0027s cause is StandbyException,\n      // return StandbyException; Otherwise, leave the exception as is,\n      // since they are handled elsewhere. See HDFS-6588.\n      if (t !\u003d null \u0026\u0026 t instanceof SecretManager.InvalidToken) {\n        final Throwable t1 \u003d t.getCause();\n        if (t1 !\u003d null \u0026\u0026 t1 instanceof StandbyException) {\n          e \u003d (StandbyException)t1;\n        }\n      }\n    } else {\n      if (t !\u003d null \u0026\u0026 t instanceof Exception) {\n        e \u003d (Exception)t;\n      }\n    }\n    return e;\n  }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/web/webhdfs/ExceptionHandler.java"
    }
  }
}