{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "FileSystemRMStateStore.java",
  "functionName": "existsWithRetries",
  "functionId": "existsWithRetries___path-Path(modifiers-final)",
  "sourceFilePath": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/FileSystemRMStateStore.java",
  "functionStartLine": 734,
  "functionEndLine": 741,
  "numCommitsSeen": 57,
  "timeTaken": 1513,
  "changeHistory": [
    "01a1621930df17a745dd37892996c68fca3447d1"
  ],
  "changeHistoryShort": {
    "01a1621930df17a745dd37892996c68fca3447d1": "Yintroduced"
  },
  "changeHistoryDetails": {
    "01a1621930df17a745dd37892996c68fca3447d1": {
      "type": "Yintroduced",
      "commitMessage": "YARN-2820. Retry in FileSystemRMStateStore when FS\u0027s operations fail due to IOException. Contributed by Zhihai Xu.\n",
      "commitDate": "27/02/15 7:56 AM",
      "commitName": "01a1621930df17a745dd37892996c68fca3447d1",
      "commitAuthor": "Tsuyoshi Ozawa",
      "diff": "@@ -0,0 +1,8 @@\n+  private boolean existsWithRetries(final Path path) throws Exception {\n+    return new FSAction\u003cBoolean\u003e() {\n+      @Override\n+      public Boolean run() throws Exception {\n+        return fs.exists(path);\n+      }\n+    }.runWithRetries();\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private boolean existsWithRetries(final Path path) throws Exception {\n    return new FSAction\u003cBoolean\u003e() {\n      @Override\n      public Boolean run() throws Exception {\n        return fs.exists(path);\n      }\n    }.runWithRetries();\n  }",
      "path": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-resourcemanager/src/main/java/org/apache/hadoop/yarn/server/resourcemanager/recovery/FileSystemRMStateStore.java"
    }
  }
}