{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "RPCUtil.java",
  "functionName": "instantiateException",
  "functionId": "instantiateException___cls-Class__? extends T____re-RemoteException",
  "sourceFilePath": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/ipc/RPCUtil.java",
  "functionStartLine": 48,
  "functionEndLine": 71,
  "numCommitsSeen": 10,
  "timeTaken": 828,
  "changeHistory": [
    "065747efabd1cbea9b14e93e905e304b9973d355"
  ],
  "changeHistoryShort": {
    "065747efabd1cbea9b14e93e905e304b9973d355": "Yintroduced"
  },
  "changeHistoryDetails": {
    "065747efabd1cbea9b14e93e905e304b9973d355": {
      "type": "Yintroduced",
      "commitMessage": "YARN-628. Fix the way YarnRemoteException is being unrolled to extract out the underlying exception. Contributed by Siddharth Seth.\n\n\ngit-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1483207 13f79535-47bb-0310-9956-ffa450edef68\n",
      "commitDate": "15/05/13 11:58 PM",
      "commitName": "065747efabd1cbea9b14e93e905e304b9973d355",
      "commitAuthor": "Vinod Kumar Vavilapalli",
      "diff": "@@ -0,0 +1,24 @@\n+  private static \u003cT extends Throwable\u003e T instantiateException(\n+      Class\u003c? extends T\u003e cls, RemoteException re) throws RemoteException {\n+    try {\n+      Constructor\u003c? extends T\u003e cn \u003d cls.getConstructor(String.class);\n+      cn.setAccessible(true);\n+      T ex \u003d cn.newInstance(re.getMessage());\n+      ex.initCause(re);\n+      return ex;\n+      // RemoteException contains useful information as against the\n+      // java.lang.reflect exceptions.\n+    } catch (NoSuchMethodException e) {\n+      throw re;\n+    } catch (IllegalArgumentException e) {\n+      throw re;\n+    } catch (SecurityException e) {\n+      throw re;\n+    } catch (InstantiationException e) {\n+      throw re;\n+    } catch (IllegalAccessException e) {\n+      throw re;\n+    } catch (InvocationTargetException e) {\n+      throw re;\n+    }\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private static \u003cT extends Throwable\u003e T instantiateException(\n      Class\u003c? extends T\u003e cls, RemoteException re) throws RemoteException {\n    try {\n      Constructor\u003c? extends T\u003e cn \u003d cls.getConstructor(String.class);\n      cn.setAccessible(true);\n      T ex \u003d cn.newInstance(re.getMessage());\n      ex.initCause(re);\n      return ex;\n      // RemoteException contains useful information as against the\n      // java.lang.reflect exceptions.\n    } catch (NoSuchMethodException e) {\n      throw re;\n    } catch (IllegalArgumentException e) {\n      throw re;\n    } catch (SecurityException e) {\n      throw re;\n    } catch (InstantiationException e) {\n      throw re;\n    } catch (IllegalAccessException e) {\n      throw re;\n    } catch (InvocationTargetException e) {\n      throw re;\n    }\n  }",
      "path": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/ipc/RPCUtil.java"
    }
  }
}