{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "RetryCache.java",
  "functionName": "lock",
  "functionId": "lock",
  "sourceFilePath": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RetryCache.java",
  "functionStartLine": 213,
  "functionEndLine": 215,
  "numCommitsSeen": 11,
  "timeTaken": 1068,
  "changeHistory": [
    "01ea6480564a9418230cd26b6f9dd54e28c51db0"
  ],
  "changeHistoryShort": {
    "01ea6480564a9418230cd26b6f9dd54e28c51db0": "Yintroduced"
  },
  "changeHistoryDetails": {
    "01ea6480564a9418230cd26b6f9dd54e28c51db0": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-6229. Race condition in failover can cause RetryCache fail to work. Contributed by Jing Zhao.\n\ngit-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1586714 13f79535-47bb-0310-9956-ffa450edef68\n",
      "commitDate": "11/04/14 9:42 AM",
      "commitName": "01ea6480564a9418230cd26b6f9dd54e28c51db0",
      "commitAuthor": "Jing Zhao",
      "diff": "@@ -0,0 +1,3 @@\n+  public void lock() {\n+    this.lock.lock();\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  public void lock() {\n    this.lock.lock();\n  }",
      "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/RetryCache.java"
    }
  }
}